version: '3.0'

expectations:
  population_size: 5000

actions:

  ## # # # # # # # # # # # # # # # # # # # 
  ## # # # # # # # # # # # # # # # # # # # 
  ## Data extraction 
  ## # # # # # # # # # # # # # # # # # # # 
  ## # # # # # # # # # # # # # # # # # # # 

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz

  generate_study_population_flowchart:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_flowchart --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_flowchart.csv.gz

  generate_study_population_pax_trt:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_pax_trt --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_pax_trt.csv.gz

  ## # # # # # # # # # # # # # # # # # # # 
  ## # # # # # # # # # # # # # # # # # # # 
  ## Data cleaning and description
  ## # # # # # # # # # # # # # # # # # # # 
  ## # # # # # # # # # # # # # # # # # # # 

  data_process:
    run: r:latest analysis/data_process.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        data1: output/data/data_processed.rds
        data2: output/data/data_processed_grace6.rds
        data3: output/data/data_processed_grace7.rds
        data4: output/data/data_processed_grace8.rds
        data1_excl: output/data/data_processed_excl_contraindicated.rds
        data2_excl: output/data/data_processed_excl_contraindicated_grace6.rds
        data3_excl: output/data/data_processed_excl_contraindicated_grace7.rds
        data4_excl: output/data/data_processed_excl_contraindicated_grace8.rds
        rds1: output/data_properties/n_excluded.rds
        rds2: output/data_properties/n_excluded_contraindicated.rds

  data_process_flowchart:
    run: r:latest analysis/data_process_flowchart.R
    needs: [generate_study_population_flowchart]
    outputs:
      highly_sensitive:
        data: output/data/data_flowchart_processed.rds
  
  data_properties:
    run: r:latest analysis/data_properties/data_properties.R output/data/data_processed.rds output/data_properties
    needs: [data_process]
    outputs:
      moderately_sensitive:
        txt1: output/data_properties/data_processed_skim.txt
        txt2: output/data_properties/data_processed_coltypes.txt
        txt3: output/data_properties/data_processed_tabulate.txt

  create_flowchart:
    run: r:latest analysis/flowchart.R
    needs: [data_process_flowchart, data_process]
    outputs:
      moderately_sensitive:
        csv1: output/flowchart/flowchart.csv
        csv2: output/flowchart/flowchart_redacted.csv

  ## # # # # # # # # # # # # # # # # # # # 
  ## # # # # # # # # # # # # # # # # # # # 
  ## Descriptive analyses
  ## # # # # # # # # # # # # # # # # # # # 
  ## # # # # # # # # # # # # # # # # # # #

  describe_distr_trt_init:
    run: r:latest analysis/descriptives/describe_distr_trt_init.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        csv1: output/descriptives/distr_pax_init.csv
        csv2: output/descriptives/distr_pax_init_red.csv

  describe_outcomes_in_trt_window:
    run: r:latest analysis/descriptives/describe_outcomes_in_trt_window.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        csv1: output/descriptives/outcomes_in_trt_window.csv
        csv2: output/descriptives/outcomes_in_trt_window_red.csv
        csv3: output/descriptives/outcomes_day0.csv
  
  describe_prop_trt:
    run: r:latest analysis/descriptives/describe_prop_trt.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        csv1: output/descriptives/prop_trt.csv
        csv2: output/descriptives/prop_trt_red.csv

  describe_trt_contra:
    run: r:latest analysis/descriptives/describe_trt_contra.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        csv1: output/descriptives/trt_contra.csv
        csv2: output/descriptives/trt_contra_red.csv
        csvs1: output/descriptives/n_codes_*.csv

  describe_trt_preds_all_ci:
    run: r:latest analysis/descriptives/describe_trt_preds.R all_ci
    needs: [data_process]
    outputs:
      highly_sensitive:
        data1: output/descriptives/psModel_all_ci.rds     
      moderately_sensitive:
        png1: output/descriptives/psOverlap_untrimmed_all_ci.png
        png2: output/descriptives/psOverlap_trimmed_all_ci.png
        png3: output/descriptives/psCoefs_all_ci.png
        csv1: output/descriptives/trimming_descriptives_all_ci.csv

  describe_trt_preds_excl_drugs_dnu:
    run: r:latest analysis/descriptives/describe_trt_preds.R ci_drugs_dnu
    needs: [data_process]
    outputs:
      highly_sensitive:
        data1: output/descriptives/psModel_excl_drugs_dnu.rds
      moderately_sensitive:
        png1: output/descriptives/psOverlap_untrimmed_excl_drugs_dnu.png
        png2: output/descriptives/psOverlap_trimmed_excl_drugs_dnu.png
        png3: output/descriptives/psCoefs_excl_drugs_dnu.png
        csv1: output/descriptives/trimming_descriptives_excl_drugs_dnu.csv
        
  create_table1:
    run: r:latest analysis/descriptives/table1.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        csv1: output/tables/table1.csv
        csv2: output/tables/table1_red.csv

  describe_trt_groups:
    run: r:latest analysis/descriptives/describe_trt_groups.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        csv1: output/descriptives/trt_groups.csv
        csv2: output/descriptives/trt_groups_red.csv
  
  describe_postest_pop:
    run: r:latest analysis/descriptives/describe_postest_pop.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        csv1: output/descriptives/postest_pop.csv
        csv2: output/descriptives/postest_pop_red.csv
    
  ## # # # # # # # # # # # # # # # # # # # 
  ## # # # # # # # # # # # # # # # # # # # 
  ## Sequential trials
  ## # # # # # # # # # # # # # # # # # # # 
  ## # # # # # # # # # # # # # # # # # # #
  data_prepare_seq_trials:
    run: r:latest analysis/seq_trials/prepare_data.R
    needs: [data_process]
    outputs:
      highly_sensitive:
        data1: output/data/data_seq_trials_monthly.feather
        data2: output/data/data_seq_trials_weekly.feather

  describe_size_trials:
    run: r:latest analysis/seq_trials/descriptives/describe_size_trials.R
    needs: [data_prepare_seq_trials]
    outputs:
      moderately_sensitive:
        csv1: output/seq_trials/descriptives/data_flow_seq_trials_monthly.csv
        csv2: output/seq_trials/descriptives/data_flow_seq_trials_weekly.csv
        csv3: output/seq_trials/descriptives/data_flow_seq_trials_monthly_red.csv
        csv4: output/seq_trials/descriptives/data_flow_seq_trials_weekly_red.csv