version: '3.0'

expectations:
  population_size: 1000

actions:

  ## # # # # # # # # # # # # # # # # # # # 
  ## # # # # # # # # # # # # # # # # # # # 
  ## Data extraction 
  ## # # # # # # # # # # # # # # # # # # # 
  ## # # # # # # # # # # # # # # # # # # # 

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input.csv.gz

  generate_study_population_flowchart:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_flowchart --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_flowchart.csv.gz

  generate_study_population_pax_trt:
    run: cohortextractor:latest generate_cohort --study-definition study_definition_pax_trt --output-format=csv.gz
    outputs:
      highly_sensitive:
        cohort: output/input_pax_trt.csv.gz

  ## # # # # # # # # # # # # # # # # # # # 
  ## # # # # # # # # # # # # # # # # # # # 
  ## Data cleaning and description
  ## # # # # # # # # # # # # # # # # # # # 
  ## # # # # # # # # # # # # # # # # # # # 

  data_process:
    run: r:latest analysis/data_process.R
    needs: [generate_study_population]
    outputs:
      highly_sensitive:
        data1: output/data/data_processed.rds
        data2: output/data/data_processed_grace6.rds
        data3: output/data/data_processed_grace7.rds
        data4: output/data/data_processed_grace8.rds
        rds1: output/data_properties/n_excluded.rds
        rds2: output/data_properties/n_excluded_contraindicated.rds

  data_process_flowchart:
    run: r:latest analysis/data_process_flowchart.R
    needs: [generate_study_population_flowchart]
    outputs:
      highly_sensitive:
        data: output/data/data_flowchart_processed.rds
  
  data_properties:
    run: r:latest analysis/data_properties/data_properties.R output/data/data_processed.rds output/data_properties
    needs: [data_process]
    outputs:
      moderately_sensitive:
        txt1: output/data_properties/data_processed_skim.txt
        txt2: output/data_properties/data_processed_coltypes.txt
        txt3: output/data_properties/data_processed_tabulate.txt

  create_flowchart:
    run: r:latest analysis/flowchart.R
    needs: [data_process_flowchart, data_process]
    outputs:
      moderately_sensitive:
        csv1: output/flowchart/flowchart.csv
        csv2: output/flowchart/flowchart_redacted.csv

  ## # # # # # # # # # # # # # # # # # # # 
  ## # # # # # # # # # # # # # # # # # # # 
  ## Descriptive analyses
  ## # # # # # # # # # # # # # # # # # # # 
  ## # # # # # # # # # # # # # # # # # # #

  describe_distr_trt_init:
    run: r:latest analysis/descriptives/describe_distr_trt_init.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        csv1: output/descriptives/distr_pax_init.csv
        csv2: output/descriptives/distr_pax_init_red.csv

  describe_outcomes_in_trt_window:
    run: r:latest analysis/descriptives/describe_outcomes_in_trt_window.R
    needs: [data_process]
    outputs:
      moderately_sensitive:
        csv1: output/descriptives/outcomes_in_trt_window.csv
        csv2: output/descriptives/outcomes_in_trt_window_red.csv