################################################################################
#
# Table 1
# 
#
# The output of this script is:
# -./output/tables/table1.csv
#
################################################################################

################################################################################
# 0.0 Import libraries + functions
################################################################################
library('tidyverse')
library('here')
library('glue')
library('gt')
library('gtsummary')
library('fs')
library('optparse')
# Import custom user functions
source(here::here("lib", "design", "covars_table.R"))
source(here::here("analysis", "descriptives", "functions", "clean_table_names.R"))

################################################################################
# 0.1 Import command-line arguments
################################################################################
args <- commandArgs(trailingOnly=TRUE)

################################################################################
# 0.2 Create directories for output
################################################################################
output_dir <- here::here("output", "tables")
fs::dir_create(output_dir)

################################################################################
# 0.3 Import data
################################################################################
data <- read_rds(here("output", "data", "data_processed_excl_contraindicated.rds"))

################################################################################
# 1 Make table 1
################################################################################
# Set rounding and redaction thresholds
rounding_threshold = 6
redaction_threshold = 8
# Format data
data_table <- 
  data %>%
  mutate(N = 1, 
         allpop = "All") %>%
  select(N, allpop, treatment_strategy_cat_prim, all_of(covars))
# Generate full and stratified table
pop_levels = c("All", "Molnupiravir", "Sotrovimab", "Paxlovid", "Untreated")
# Generate table - full and stratified populations
for (pop_level in pop_levels) {
  if (pop_level != "All"){
    data_summary <-
      data_table %>%
      filter(treatment_strategy_cat_prim == pop_level)
  } else data_summary <- data_table
  data_summary <- 
    data_summary %>% 
    select(-treatment_strategy_cat_prim) %>% 
    tbl_summary(by = allpop,
                statistic = everything() ~ "{n}")
  table1 <- 
    data_summary$table_body %>%
    filter(!is.na(stat_1)) %>%
    mutate(label = if_else(var_type == "dichotomous", "", label)) %>%
    select(group = variable, variable = label, count = stat_1) %>%
    mutate(count = case_when(!is.na(count) ~ as.numeric(gsub(",", "", count)),
                             TRUE ~ NA_real_)) %>%
    mutate(percent = round(count / data_summary$N * 100, 1)) %>%
    clean_table_names()
  # Calculate rounded total
  rounded_n = plyr::round_any(data_summary$N, rounding_threshold)
  # Round individual values to rounding threshold
  table1_redacted <- table1 %>%
    mutate(count = plyr::round_any(count, rounding_threshold),
           percent = round(count / rounded_n * 100, 1),
           non_count = rounded_n - count)
  # Redact any rows with rounded cell data or non-data <= redaction threshold
  table1_redacted <-
    table1_redacted %>%
    mutate(summary = paste0(prettyNum(count, big.mark=","),
                            " (",
                            format(percent, nsmall = 1), "%)") %>%
             gsub(" ", "", .,  fixed = TRUE) %>% # Remove spaces generated by decimal formatting
             gsub("(", " (", ., fixed = TRUE)) %>% # Add first space before (
    mutate(summary = if_else((count >= 0 & count <= redaction_threshold) | 
                               (non_count >= 0 & non_count <= redaction_threshold),
                             "[Redacted]", 
                             summary)) %>%
    mutate(summary = if_else(group == "N",
                             prettyNum(count, big.mark = ","),
                             summary)) %>%
    select(-non_count, -count, -percent) %>%
    rename("{pop_level}" := summary)
  table1 <-
    table1 %>%
    select(-percent) %>%
    rename("{pop_level}" := count)
  # collate table
  if (pop_level == "All") { 
    collated_table = table1_redacted 
    collated_table_unred = table1
  } else { 
    collated_table = collated_table %>% 
      left_join(table1_redacted, 
                by = c("group", "variable"))
    collated_table_unred = collated_table_unred %>% 
      left_join(table1, 
                by = c("group", "variable"))
  }
}

################################################################################
# 2 Save table
################################################################################
write_csv(collated_table_unred,
          fs::path(output_dir, "table1.csv"))
write_csv(collated_table,
          fs::path(output_dir, "table1_red.csv"))
